#define OFXDIGITALEMULSION_VERSION_MAJOR 0
#define OFXDIGITALEMULSION_VERSION_MINOR 3
#define OFXDIGITALEMULSION_VERSION_POSTFIX "alpha"

#define OFXDIGITALEMULSION_VERSION_STRING ofToString(OFXDIGITALEMULSION_VERSION_MAJOR) + "." + ofToString(OFXDIGITALEMULSION_VERSION_MINOR) + OFXDIGITALEMULSION_VERSION_POSTFIX
