#include "pch_Plugin_LSS.h"


OFXPLUGIN_PLUGIN_MODULES_BEGIN(ofxRulr::Nodes::Base)
{
	OFXPLUGIN_PLUGIN_REGISTER_MODULE(ofxRulr::Nodes::LSS::World);
	OFXPLUGIN_PLUGIN_REGISTER_MODULE(ofxRulr::Nodes::LSS::Projector);
	OFXPLUGIN_PLUGIN_REGISTER_MODULE(ofxRulr::Nodes::LSS::Scan);
	OFXPLUGIN_PLUGIN_REGISTER_MODULE(ofxRulr::Nodes::LSS::FitLines);
}
OFXPLUGIN_PLUGIN_MODULES_END