#define RULR_VERSION_MAJOR 23
#define RULR_VERSION_MINOR 8
#define RULR_VERSION_POSTFIX "a"

#define RULR_VERSION_STRING ofToString(RULR_VERSION_MAJOR) + "." + ofToString(RULR_VERSION_MINOR) + RULR_VERSION_POSTFIX
