#define RULR_VERSION_MAJOR 0
#define RULR_VERSION_MINOR 5
#define RULR_VERSION_POSTFIX "a"

#define RULR_VERSION_STRING ofToString(RULR_VERSION_MAJOR) + "." + ofToString(RULR_VERSION_MINOR) + RULR_VERSION_POSTFIX
