#define RULR_VERSION_MAJOR 0
#define RULR_VERSION_MINOR 4
#define RULR_VERSION_POSTFIX "alpha_NOPLUGINS"

#define RULR_VERSION_STRING ofToString(RULR_VERSION_MAJOR) + "." + ofToString(RULR_VERSION_MINOR) + RULR_VERSION_POSTFIX
