#define RULR_VERSION_MAJOR 0
#define RULR_VERSION_MINOR 3
#define RULR_VERSION_POSTFIX "alpha"

#define RULR_VERSION_STRING ofToString(RULR_VERSION_MAJOR) + "." + ofToString(RULR_VERSION_MINOR) + RULR_VERSION_POSTFIX
